bids_dir: /nfs/khan/datasets/histo2mri/cfmm2bids/results/4_fix/bids
derivatives: 
 - /nfs/khan/datasets/histo2mri/derivatives
 - transforms



pybids_inputs:
  dwi:
    filters:
      suffix: dwi
      extension: .nii.gz
      datatype: dwi
      subject: CAD02
      desc: eddy
    wildcards: 
      - subject
      - session
  dseg:
    filters:
      suffix: dseg
      extension: .nii.gz
      datatype: anat
      space: T2starw
    wildcards: 
      - subject
      - session
      - desc
  xfm_to_dwi:
    filters:
      suffix: xfm
      extension: .txt
      datatype: dwi
      from: T2starw
      to: dwi
      desc: itk
    wildcards: 
      - subject
      - session


downsample_res:
  - 0p2mm
#  - 0p4mm
  - 0p5mm
  - 1mm
  - 1p25mm
  - 1p5mm
  - 2mm

tracking:
  seedmask:
    - brain
#    - thFA0p3
  select: 
    - 5000
  algo:
    - det
#    - prob


clustering:
  points:
    - 100
  scalargroups:
    geom:
      - coord0
      - coord1
      - coord2
    all:
      - FA
      - AD
      - RD
      - ADC
      - coord0
      - coord1
      - coord2

