bids_dir: /nfs/khan/datasets/histo2mri/cfmm2bids/results/4_fix/bids
derivatives: 
 - /nfs/khan/datasets/histo2mri/derivatives
 - transforms


pybids_inputs:
  t1w:
    filters:
      suffix: MEGRE # change
      extension: .nii.gz
      datatype: anat
      subject: CAD01 # change
      run: 1
      echo: 3 # change
    wildcards:
      - subject
      - session
  dwi:
    filters:
      suffix: dwi
      extension: .nii.gz
      datatype: dwi
      subject: CAD01 # change
      desc: eddy
    wildcards: 
      - subject
      - session
  dseg:
    filters:
      suffix: dseg
      extension: .nii.gz
      datatype: anat
      space: T1w # change
      desc: NextBrain
    wildcards: 
      - subject
      - session

  # xfm_to_dwi:
  #   filters:
  #     suffix: xfm
  #     extension: .txt
  #     datatype: dwi
  #     from: T2starw
  #     to: dwi
  #     desc: itk
  #   wildcards: 
  #     - subject
  #     - session


downsample_res:
  - 0p2mm
#  - 0p4mm
#  - 0p5mm
  - 1mm
#  - 1p25mm
#  - 1p5mm
  - 2mm

tracking:
  seedmask:
    - brain
#    - thFA0p3
  select: 
#    - 5000
    - 500000
  algo:
    - det
    - prob


clustering:
  points:
    - 100
  scalargroups:
    geom:
      - coord0
      - coord1
      - coord2
    all:
      - FA
      - AD
      - RD
      - ADC
      - coord0
      - coord1
      - coord2

connectome:
  nodes: 
    - GM
  node_start: [8,16,18] # CAD01: GPi,ZI,VTA
  node_end: [222, 283, 314, 350, 381, 382]